### PR TITLE
Add Acer UWA5 to working list

### PR DESCRIPTION
**Pull request by extremegrief1**

### CODE REVIEW

**Comment by chris1111** [comment]
Can you explain to me what Realtek drivers we have to do here with the Acer UWA5 adapter
[you don't answer here](https://github.com/extremegrief1/Wireless-USB-OC-Big-Sur-Adapter/commit/a95247f5d6e64725612836c26b9cc513c5ed217a#commitcomment-83593480)

**Comment by extremegrief1** [comment]
@chris1111 

The Acer UWA5 dongle uses the Realtek RTL8822CU chipset.

**Comment by chris1111** [comment]
were do see this?

**Comment by extremegrief1** [comment]
lspci in Linux.

**Comment by chris1111** [comment]
Show me that I see

**Pull request merged**
